export const projects = [
  {
    title: "Motion Study",
    image: "./public/img1.jpeg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Idle Form",
    image: "./public/img2.png",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Blur Signal",
    image: "./public/img3.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Still Drift",
    image: "./public/img4.png",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Silent Horizon",
    image: "./public/img5.png",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Neon Pulse",
    image: "./public/img6.png",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Echo Frame",
    image: "./public/img7.png",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Lunar Static",
    image: "./public/img8.png",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Crimson Fade",
    image: "./public/img9.png",
    year: 2021,
    href: "./sample-project.html",
  },
  {
    title: "Golden Offset",
    image: "./public/img10.png",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Phantom Grid",
    image: "./public/img11.png",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Velvet Noise",
    image: "./public/img12.png",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Glass Spectrum",
    image: "./public/img13.png",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Shadow Bloom",
    image: "./public/img14.png",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Digital Mirage",
    image: "./public/img15.png",
    year: 2021,
    href: "./sample-project.html",
  },
  {
    title: "Static Bloom",
    image: "./public/img16.png",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Midnight Vector",
    image: "./public/img17.png",
    year: 2024,
    href: "./sample-project.html",
  },
  {
    title: "Silver Current",
    image: "./public/img18.png",
    year: 2022,
    href: "./sample-project.html",
  },
  {
    title: "Urban Flux",
    image: "./public/img19.jpg",
    year: 2023,
    href: "./sample-project.html",
  },
  {
    title: "Aurora Shift",
    image: "./public/img20.jpg",
    year: 2024,
    href: "./sample-project.html",
  },
];