export interface Project {
   title: string;
   image: string;
   year: number;
   href: string;
   slug: string;
   bgColor: string;
}

export const projects: Project[] = [
   {
      title: "Motion Study",
      image: "/assets/img1.jpeg",
      year: 2024,
      href: "/projects/motion-study",
      slug: "motion-study",
      bgColor: "#2a2a2a",
   },
   {
      title: "Idle Form",
      image: "/assets/img2.png",
      year: 2023,
      href: "/projects/idle-form",
      slug: "idle-form",
      bgColor: "#1a1c29",
   },
   {
      title: "Blur Signal",
      image: "/assets/img3.png",
      year: 2024,
      href: "/projects/blur-signal",
      slug: "blur-signal",
      bgColor: "#2d1b1b",
   },
   {
      title: "Still Drift",
      image: "/assets/img4.png",
      year: 2023,
      href: "/projects/still-drift",
      slug: "still-drift",
      bgColor: "#1e3025",
   },
   {
      title: "Silent Horizon",
      image: "/assets/img5.png",
      year: 2024,
      href: "/projects/silent-horizon",
      slug: "silent-horizon",
      bgColor: "#1c2136",
   },
   {
      title: "Neon Pulse",
      image: "/assets/img6.png",
      year: 2022,
      href: "/projects/neon-pulse",
      slug: "neon-pulse",
      bgColor: "#361c33",
   },
   {
      title: "Echo Frame",
      image: "/assets/img7.png",
      year: 2023,
      href: "/projects/echo-frame",
      slug: "echo-frame",
      bgColor: "#2e2520",
   },
   {
      title: "Lunar Static",
      image: "/assets/img8.png",
      year: 2024,
      href: "/projects/lunar-static",
      slug: "lunar-static",
      bgColor: "#282a30",
   },
   {
      title: "Crimson Fade",
      image: "/assets/img9.png",
      year: 2021,
      href: "/projects/crimson-fade",
      slug: "crimson-fade",
      bgColor: "#3c1818",
   },
   {
      title: "Golden Offset",
      image: "/assets/img10.png",
      year: 2022,
      href: "/projects/golden-offset",
      slug: "golden-offset",
      bgColor: "#332d18",
   },
   {
      title: "Phantom Grid",
      image: "/assets/img11.png",
      year: 2024,
      href: "/projects/phantom-grid",
      slug: "phantom-grid",
      bgColor: "#14252a",
   },
   {
      title: "Velvet Noise",
      image: "/assets/img12.png",
      year: 2023,
      href: "/projects/velvet-noise",
      slug: "velvet-noise",
      bgColor: "#291629",
   },
   {
      title: "Glass Spectrum",
      image: "/assets/img13.png",
      year: 2022,
      href: "/projects/glass-spectrum",
      slug: "glass-spectrum",
      bgColor: "#162829",
   },
   {
      title: "Shadow Bloom",
      image: "/assets/img14.png",
      year: 2024,
      href: "/projects/shadow-bloom",
      slug: "shadow-bloom",
      bgColor: "#20222a",
   },
   {
      title: "Digital Mirage",
      image: "/assets/img15.png",
      year: 2021,
      href: "/projects/digital-mirage",
      slug: "digital-mirage",
      bgColor: "#23261f",
   },
   {
      title: "Static Bloom",
      image: "/assets/img16.png",
      year: 2023,
      href: "/projects/static-bloom",
      slug: "static-bloom",
      bgColor: "#2a1e1d",
   },
   {
      title: "Midnight Vector",
      image: "/assets/img17.png",
      year: 2024,
      href: "/projects/midnight-vector",
      slug: "midnight-vector",
      bgColor: "#16182c",
   },
   {
      title: "Silver Current",
      image: "/assets/img18.png",
      year: 2022,
      href: "/projects/silver-current",
      slug: "silver-current",
      bgColor: "#262b32",
   },
   {
      title: "Urban Flux",
      image: "/assets/img19.png",
      year: 2023,
      href: "/projects/urban-flux",
      slug: "urban-flux",
      bgColor: "#24201c",
   },
   {
      title: "Aurora Shift",
      image: "/assets/img20.png",
      year: 2024,
      href: "/projects/aurora-shift",
      slug: "aurora-shift",
      bgColor: "#1a2a1a",
   },
];
